# This is a basic workflow to help you get started with Actions

name: main-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  REPO_SECRET: ${{secrets.REPO_SECRET}}
jobs:
  front-build:
    runs-on: ubuntu-latest
    needs: back-build
    environment: dev
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - shell: bash
        name: Run a YOUR_SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"
      - shell: bash
        name: Run a REPO_SECRET
        run: |
          echo "test, and deploy your project ${{ env.REPO_SECRET }}"

  back-build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - shell: bash
        name: Run a YOUR_SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"
      - shell: bash
        name: Run a REPO_SECRET
        run: |
          echo "test, and deploy your project ${{ env.REPO_SECRET }}"
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt
          retention-days: 1

  front-test:
    needs: front-build
    environment: test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - shell: bash
        name: Run a SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
      - name: Download a single artifact
        uses: actions/download-artifact@v4.1.7

  back-test:
    needs: back-build
    environment: test
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - shell: bash
        name: Run a SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage-report
      #     path: output/test/code-coverage.html
      #     retention-days: 5

      - name: Download math result
        uses: actions/download-artifact@v4.1.7
        with:
          name: homework
      - name: Print the final result homework
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value

  front-app-prod:
    needs:
      - back-test
      - front-test
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - shell: bash
        name: Run a SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"
          echo "test, and deploy your project ${{ env.REPO_SECRET }}"
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage-report
      #     path: output/test/code-coverage.html
      #     retention-days: 5

      - name: Download math result
        uses: actions/download-artifact@v4.1.7
        with:
          name: homework
      - name: Print the final result homework
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value

  back-app-prod:
    needs:
      - back-test
      - front-test
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - shell: bash
        name: Run a SECRET
        run: |
          echo "Add other actions to build ${{ secrets.YOUR_SECRET }}"
          echo "test, and deploy your project ${{ env.REPO_SECRET }}"
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage-report
      #     path: output/test/code-coverage.html
      #     retention-days: 5

      - name: Download math result
        uses: actions/download-artifact@v4.1.7
        with:
          name: homework
      - name: Print the final result homework
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
